### ISSUE TITLE
different behavior of ncclimo (v5.2.9) in the splitting mode

### ISSUE THREAD

**Issue by minxu74** [nco/nco#289] opened 2024-12-09 15:49 UTC
When I used to ncclimo version 5.2.9 to split raw E3SM outputs, I found that its behavior differed from the previous versions. For example:
```
cd $drc_in;ls *mdl*000[1-9]*.nc | ncclimo --split -v T,Q,RH -s 1 -e 9 -o $drc_out
```
If the variable "Q" is NOT in the mdl*.nc files, the old version ncclimo (v5.0.1) will ignore the error and continue to split other variables in the background parallelism. But the version 5.2.9 will throw an error and stop splitting other variables.  For my use case, I prefer to letting the splitting continue despite the missing variables.  Thanks.

**Comment by czender** [comment] 2024-12-14 00:17
Hi @minxu74. I received this issue while I was at AGU24. Next week I'll definitely look into whether I can revert to the older behavior. However, there are some new features that make this more complex than a simple reversion. I'll post again when I have made progress.

**Comment by czender** [comment] 2024-12-17 21:48
@minxu74 I can reproduce the behavior you report. The behavior changed in June when I added support for the `--xcl_var` option in timeseries mode. The behavior changed due to some necessary changes in the handling of variable lists for timeseries. I do not consider the current behavior a bug, though I'm happy to work with you until you get a behavior you can live with.
First, did you know that timeseries mode will silent skip over missing variables if you prefix the name of each potentially missing variable with a dot? e.g.
`cd $drc_in;ls *mdl*000[1-9]*.nc | ncclimo --split -v T,.Q,RH -s 1 -e 9 -o $drc_out`
Would implementing that modification to your variable lists work for you? I seem to remember discussing this feature in the past with you, and I need to ask because that would be the simplest solution since it already works. Feedback welcome.

**Comment by minxu74** [comment] 2024-12-18 02:34
@czender Thanks a lot for your quick response. The issue just is the different behavior between two versions. I do not think it is a bug either. It is great to know there is already a solution available by adding dots before variable names. Sorry, I cannot recall the feature. The solution is what I want since it is easy for me to add dot to each variable in my workflow.  I think we can close the issue. Thanks again.

**Comment by czender** [comment] 2024-12-18 03:26
Great, I'm closing the issue.

**Closed by czender** 2024-12-18 03:26 UTC

**Comment by chengzhuzhang** [comment] 2024-12-18 17:35
> First, did you know that timeseries mode will silent skip over missing variables if you prefix the name of each potentially missing variable with a dot? e.g.
> `cd $drc_in;ls *mdl*000[1-9]*.nc | ncclimo --split -v T,.Q,RH -s 1 -e 9 -o $drc_out`
> Would implementing that modification to your variable lists work for you? I seem to remember discussing this feature in the past with you, and I need to ask because that would be the simplest solution since it already works

hey @czender I just came cross this thread and curious about this new development. I think the previous syntax for accommodating potential missing variable is something like`^Q$`, I'm curious if `.Q` replaces the old syntax? Thank you.

**Comment by czender** [comment] 2024-12-18 18:08
Hi @chengzhuzhang,
I'm glad you chimed in about that old thread. The method that you mention for ncclimo to tolerate missing variables is `^var_name$` whereas the method I suggested to @minxu74 is `.var_name`. Both of these are different uses of the regular expression feature of NCO. `^var_name$` will match and therefore include only a variable whose name is exactly `var_name` and it will tolerate the absence of that variable. `^var_name$` will match and therefore include variables with names such as `AQ`, `BQ`, ..., and, of course `Q`, and tolerate the absence of any such variables. Use the regular expression that best suits your needs.
