### ISSUE TITLE
ncks produces 0 for area on mac 10.10.3

### ISSUE THREAD

**Issue by doutriaux1** [nco/nco#9] opened 2015-06-16 22:03 UTC
```
ncks -O --map=/Users/doutriaux1/map_ne30np4_to_fv257x512_bilin.150418.nc /Users/doutriaux1/famipc5_ne30_v0.3_00003.cam.h0.1979-01.nc test_regrid_nco.nc
```
using tag point 4.5.0

**Comment by czender** [comment] 2015-06-17 20:01
This appears to have been caused by a buffer overrun that was fixed in just tagged alpha3. Works on my mac. Please try again and close if it works or send me more info if it doesn't.

**Comment by doutriaux1** [comment] 2015-06-18 16:18
@czender I just built off of master on another mac: 10.9.5

I get zeros for area, should I get another branch?

**Comment by doutriaux1** [comment] 2015-06-18 16:25
got the same answer with the tag 4.5.1-alpha3

**Comment by doutriaux1** [comment] 2015-06-18 16:32
also still same issue on 10.10.3

**Comment by doutriaux1** [comment] 2015-06-18 16:33
other variables appear to be blank as well but not all

**Comment by czender** [comment] 2015-06-18 18:46
thanks for trying the update on your mac. i added regridding regression tests so i know it definitely works with my mac in the macports environment (using clang+netCDF4.3.3.1). those tests are expensive becaue they scp  map and data files to the local machine, so they are turned-off for everyone but me. i'll tweak them so they run for anyone, and then i'll ask you to run them. what is your compiler? what is your mac environment (basic Xcode, macports, etc.)? could you please check if the problem is threading by running the ncks regrid command with -t 1. and could you please run 'make test' and post the result. thx.

**Comment by doutriaux1** [comment] 2015-06-18 19:24
@czender on mac 10.9:
```
doutriaux1@maryam:[uvcdat]:[9694]> xcodebuild -version
Xcode 5.1.1
Build version 5B1008
```
on mac 10.10
```
doutriaux1@sofia:[~]:[7232]> xcodebuild -version
Xcode 6.3.1
Build version 6D1002
```

**Comment by doutriaux1** [comment] 2015-06-18 19:26
10.10
```
doutriaux1@sofia:[nco]:[master]:[7231]> make test
/Applications/Xcode.app/Contents/Developer/usr/bin/make check
Making check in data
make[2]: Nothing to be done for `check'.
Making check in src
Making check in nco
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
============================================================================
Testsuite summary for NCO netCDF Operators 4.5.1-alpha4
============================================================================
# TOTAL: 0
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in nco_c++
/Applications/Xcode.app/Contents/Developer/usr/bin/make  tst
g++ -DHAVE_CONFIG_H -I. -I../..   -I/lgm/uvcdat/parallel/Externals/include -I/lgm/uvcdat/parallel/Externals/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -m64 -mmacosx-version-min=10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -pipe -I/lgm/uvcdat/parallel/Externals/include   -g -O2 -MT tst.o -MD -MP -MF .deps/tst.Tpo -c -o tst.o tst.cc
mv -f .deps/tst.Tpo .deps/tst.Po
/bin/sh ../../libtool --tag=CXX  --tag=CXX   --mode=link g++  -g -O2  -L/lgm/uvcdat/parallel/Externals/lib -lnetcdf -L/lgm/uvcdat/parallel/Externals/lib  -o tst tst.o -lnco_c++ -ludunits2 -lexpat -lresolv -lm -lnetcdf -lnetcdf -lnetcdf  -lcurl -ludunits2
libtool: link: g++ -g -O2 -o tst tst.o -Wl,-bind_at_load  -L/lgm/uvcdat/parallel/Externals/lib /git/nco/src/nco_c++/.libs/libnco_c++.a -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources -lresolv /lgm/uvcdat/parallel/Externals/lib/libnetcdf.dylib /lgm/uvcdat/parallel/Externals/lib/libhdf5_hl.dylib /lgm/uvcdat/parallel/Externals/lib/libhdf5.dylib -ldl -lm -lz -lcurl /lgm/uvcdat/parallel/Externals/lib/libudunits2.dylib -lexpat
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
../../autobld/test-driver: line 95: 24859 Abort trap: 6           "$@" > $log_file 2>&1
FAIL: tst
============================================================================
Testsuite summary for NCO netCDF Operators 4.5.1-alpha4
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/nco_c++/test-suite.log
Please report to nco-bugs@lists.sourceforge.net
============================================================================
make[5]: *** [test-suite.log] Error 1
make[4]: *** [check-TESTS] Error 2
make[3]: *** [check-am] Error 2
make[2]: *** [check-recursive] Error 1
make[1]: *** [check-recursive] Error 1
make: *** [tst] Error 2
```

**Comment by doutriaux1** [comment] 2015-06-18 19:26
mac 10.9
```
doutriaux1@maryam:[nco]:[9685]> make test
/Applications/Xcode.app/Contents/Developer/usr/bin/make check
Making check in data
make[2]: Nothing to be done for `check'.
Making check in src
Making check in nco
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
============================================================================
Testsuite summary for NCO netCDF Operators 4.5.1-alpha3
============================================================================
# TOTAL: 0
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in nco_c++
/Applications/Xcode.app/Contents/Developer/usr/bin/make  tst
g++ -DHAVE_CONFIG_H -I. -I../..   -I/lgm/uvcdat/2015-06-14/Externals/include -I/lgm/uvcdat/2015-06-14/Externals/include   -g -O2 -MT tst.o -MD -MP -MF .deps/tst.Tpo -c -o tst.o tst.cc
mv -f .deps/tst.Tpo .deps/tst.Po
/bin/sh ../../libtool --tag=CXX  --tag=CXX   --mode=link g++  -g -O2  -L/lgm/uvcdat/2015-06-14/Externals/lib -lnetcdf -lhdf5_hl -lhdf5 -lz -ldl -lm -lcurl -L/lgm/uvcdat/2015-06-14/Externals/lib  -o tst tst.o -lnco_c++ -ludunits2 -lexpat -lresolv -lm -lnetcdf -lnetcdf -lnetcdf  -lcurl -ludunits2
libtool: link: g++ -g -O2 -o tst tst.o -Wl,-bind_at_load  -L/lgm/uvcdat/2015-06-14/Externals/lib -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources -L/lgm/uvcdat/2015-06-14/Externals/lib64 /git/nco/src/nco_c++/.libs/libnco_c++.a -lresolv /lgm/uvcdat/2015-06-14/Externals/lib/libnetcdf.dylib /lgm/uvcdat/2015-06-14/Externals/lib/libhdf5_hl.dylib /lgm/uvcdat/2015-06-14/Externals/lib/libhdf5.dylib -ldl -lm -lz -lcurl /lgm/uvcdat/2015-06-14/Externals/lib/libudunits2.dylib -lexpat
ld: warning: directory not found for option '-L/lgm/uvcdat/2015-06-14/Externals/lib64'
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
../../autobld/test-driver: line 95: 20703 Trace/BPT trap: 5       "$@" > $log_file 2>&1
FAIL: tst
============================================================================
Testsuite summary for NCO netCDF Operators 4.5.1-alpha3
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/nco_c++/test-suite.log
Please report to nco-bugs@lists.sourceforge.net
============================================================================
make[5]: *** [test-suite.log] Error 1
make[4]: *** [check-TESTS] Error 2
make[3]: *** [check-am] Error 2
make[2]: *** [check-recursive] Error 1
make[1]: *** [check-recursive] Error 1
make: *** [tst] Error 2
```

**Comment by czender** [comment] 2015-06-18 19:29
thanks. it's difficult to debug when i can't reproduce the problem, so i just compiled with clang on linux and it sure-enough it flagged a problem that i think could explain the symptoms you see. will post again if/when i've had a chance to track it down and fix it.

**Comment by czender** [comment] 2015-06-19 15:52
have pushed a new tag, 4.5.1-alpha4, that may fix the problem. would appreciate any feedback on how it works for you.

**Comment by czender** [comment] 2015-07-17 20:36
do you still get zeros or wrong answers on macos? otherwise please close this issue. thx,c

**Comment by doutriaux1** [comment] 2015-07-20 14:33
sorry, didn't retry it yet. Will do today.

**Comment by doutriaux1** [comment] 2015-07-21 23:44
@czender fresh build off of master:
```
ncks -O --map=/Users/doutriaux1/map_ne30np4_to_fv257x512_bilin.150418.nc /Users/doutriaux1/famipc5_ne30_v0.3_00003.cam.h0.1979-01.nc test_regrid_nco.nc
ncks: ERROR nco_rgr_map() reports area_out contains zero-element at 1D idx=0
```

**Comment by czender** [comment] 2015-07-22 23:22
thanks for reporting this. think i boke that in alpha1, should be fixed now in alpha5, just released. also added bilinear interpolation to my regression tests. didn't realize how different those mapfiles are compared to conservative remapping until this happened. would appreciate if you build and try again. 
c

**Comment by czender** [comment] 2015-11-11 19:39
This was presumably solved 7/22.

**Closed by czender** 2015-11-11 19:39 UTC
