### ISSUE TITLE
ncwa process 'killed'

### ISSUE THREAD

**Issue by areminusfarestar** [nco/nco#202] opened 2020-07-23 19:18 UTC
Hi Charlie, 
Matt Huber here.  I have some ERA5 data, when I use ncwa -a time (to create a time average), the process is killed and generates a small .tmp file. This is even when running on a relatively small 2GB subset file. The cluster node I'm running on has 24 cores/256GB RAM so I don't think it's a RAM issue (I also verified on different nodes, and using slightly different versions of netcdf/nco).  

Interestingly when I   do this "ncks --mk_rec_dmn time era5_fluxes.nc era5_fluxes_time.nc" and instead run ncra on the exact same file, there's no problem, output is generated as normal.

ncdump -h on the original file that ncwa -a time fails on, and the result from ncwa ―revision follow.

――――――-
netcdf era5_fluxes {
dimensions:
        longitude = 1440 ;
        latitude = 721 ;
        expver = 2 ;
        time = 498 ;
variables:
                msshf:_FillValue = -32767s ;
                msshf:missing_value = -32767s ;
                msshf:units = "W m**-2" ;
                msshf:long_name = "Mean surface sensible heat flux" ;
        short wind(time, expver, latitude, longitude) ;
                wind:scale_factor = 0.000236697154248623 ;
                wind:add_offset = 9.75561895611037 ;
                wind:_FillValue = -32767s ;
                wind:missing_value = -32767s ;
                wind:units = "m s**-1" ;
                wind:long_name = "10 metre wind speed" ;
        short pev(time, expver, latitude, longitude) ;
                pev:scale_factor = 2.46959125306389e-07 ;
                pev:add_offset = -0.00686471218724812 ;
                pev:_FillValue = -32767s ;
                pev:missing_value = -32767s ;
                pev:units = "m" ;
                pev:long_name = "Potential evaporation" ;
        short sst(time, expver, latitude, longitude) ;
                sst:scale_factor = 0.00061697729459776 ;
                sst:add_offset = 289.46490147229 ;
                sst:_FillValue = -32767s ;
                sst:missing_value = -32767s ;
                sst:units = "K" ;
                sst:long_name = "Sea surface temperature" ;
        short skt(time, expver, latitude, longitude) ;
                skt:scale_factor = 0.0018767493273904 ;
                skt:add_offset = 257.710975687836 ;
                skt:_FillValue = -32767s ;
                skt:missing_value = -32767s ;
                skt:units = "K" ;
                skt:long_name = "Skin temperature" ;
        short slhf(time, expver, latitude, longitude) ;
                slhf:scale_factor = 857.234797735492 ;
                slhf:add_offset = -23170148.6173989 ;
                slhf:_FillValue = -32767s ;
                slhf:missing_value = -32767s ;
                slhf:units = "J m**-2" ;
                slhf:long_name = "Surface latent heat flux" ;
                slhf:standard_name = "surface_upward_latent_heat_flux" ;
        short ssr(time, expver, latitude, longitude) ;
                ssr:scale_factor = 490.670898631224 ;
                ssr:add_offset = 16077322.6645507 ;
                ssr:_FillValue = -32767s ;
                ssr:missing_value = -32767s ;
                ssr:units = "J m**-2" ;
                ssr:long_name = "Surface net solar radiation" ;
                ssr:standard_name = "surface_net_downward_shortwave_flux" ;
        short str(time, expver, latitude, longitude) ;
                str:scale_factor = 324.803274686036 ;
                str:add_offset = -8457207.90163734 ;
                str:_FillValue = -32767s ;
                str:missing_value = -32767s ;
                str:units = "J m**-2" ;
                str:long_name = "Surface net thermal radiation" ;
                str:standard_name = "surface_net_upward_longwave_flux" ;
        short sp(time, expver, latitude, longitude) ;
                sp:scale_factor = 0.862912995647231 ;
                sp:add_offset = 76378.4611216272 ;
                sp:_FillValue = -32767s ;
                sp:missing_value = -32767s ;
                sp:units = "Pa" ;
                sp:long_name = "Surface pressure" ;
                sp:standard_name = "surface_air_pressure" ;
        short sshf(time, expver, latitude, longitude) ;
                sshf:scale_factor = 808.723665939298 ;
                sshf:add_offset = -18252976.361833 ;
                sshf:_FillValue = -32767s ;
                sshf:missing_value = -32767s ;
                sshf:units = "J m**-2" ;
                sshf:long_name = "Surface sensible heat flux" ;
                sshf:standard_name = "surface_upward_sensible_heat_flux" ;

// global attributes:
                :Conventions = "CF-1.6" ;
                :history = "2020-07-20 20:11:07 GMT by grib_to_netcdf-2.16.0: /opt/ecmwf/eccodes/bin/grib_to_netcdf -S param -o /cache/data3/adaptor.mars.internal-1595273624.351211-13823-13-54b3273a-04d3-401c-8cc2-aa29c1e8dd94.nc /cache/tmp/54b3273a-04d3-401c-8cc2-aa29c1e8dd94-adaptor.mars.internal-1595273624.3517582-13823-4-tmp.grib" ;
―――――-
NCO netCDF Operators version 4.6.7 built by rcactest on brown-a148 at Apr 26 2020 19:55:10
ncwa version 4.6.7
Linked to netCDF library version 4.5.0 compiled Apr 26 2020 03:52:09
Copyright (C) 1995--2017 Charlie Zender
This program is part of NCO, the netCDF Operators.
NCO is free software and comes with a BIG FAT KISS and ABOLUTELY NO WARRANTY
You may redistribute and/or modify NCO under the terms of the
GNU General Public License (GPL) Version 3 with exceptions described in the LICENSE file
GPL: http://www.gnu.org/copyleft/gpl.html
LICENSE: https://github.com/nco/nco/tree/master/LICENSE
Homepage: http://nco.sf.net
User Guide: http://nco.sf.net/nco.html
Configuration Option:   Active? Meaning or Reference:
Check _FillValue        Yes     http://nco.sf.net/nco.html#mss_val
Check missing_value     No      http://nco.sf.net/nco.html#mss_val
DAP clients             No      http://nco.sf.net/nco.html#dap
Debugging: Custom       No      Pedantic, bounds checking (slowest execution)
Debugging: Symbols      No      Produce symbols for debuggers (e.g., dbx, gdb)
ESMF Library            No      http://nco.sf.net/nco.html#esmf
GNU Scientific Library  Yes     http://nco.sf.net/nco.html#gsl
HDF4 support            Yes     http://nco.sf.net/nco.html#hdf4
Internationalization    No      http://nco.sf.net/nco.html#i18n (pre-alpha)
MPI parallelization     No      http://nco.sf.net/nco.html#mpi (beta)
netCDF3 64-bit files    Yes     http://nco.sf.net/nco.html#lfs
netCDF4/HDF5 available  Yes     http://nco.sf.net/nco.html#nco4
netCDF4/HDF5 enabled    Yes     http://nco.sf.net/nco.html#nco4
OpenMP SMP threading    Yes     http://nco.sf.net/nco.html#omp
Optimization: run-time  No      Fastest execution possible (slowest compilation)
Parallel netCDF3        No      http://nco.sf.net/nco.html#pnetcdf (pre-alpha)
Regular Expressions     Yes     http://nco.sf.net/nco.html#rx
Shared libraries built  Yes     Small, dynamically linked executables
Static libraries built  Yes     Large executables with private namespaces
UDUnits conversions     Yes     http://nco.sf.net/nco.html#udunits
UDUnits2 conversions    Yes     http://nco.sf.net/nco.html#udunits

Shots and power tools

**Comment by czender** [comment] 2020-07-23 20:01
Hi Matt,
You are using too old an NCO for me to trust. Please first verify that the latest stable version, 4.9.3, reproduces the problem. You can easily install it with Anaconda, e.g.,
Charlie

**Comment by czender** [comment] 2020-07-23 23:37
http://nco.sf.net/nco.html#ulimit
http://nco.sf.net/nco.html#mmr_ncwa

**Comment by czender** [comment] 2020-09-21 12:43
Closing, unable to reproduce without more info/effort

**Closed by czender** 2020-09-21 12:43 UTC
Labels: unreproducible
