### ISSUE TITLE
nco_put_vara() failed to nc_put_vara() variable "xps_img"

### ISSUE THREAD

**Issue by Paheding** [nco/nco#115] opened 2019-02-07 16:20 UTC
It seems the issue was raised when the raw data were translated into the NCO. Based on a more complete error readout (below) this seems to be the key problem:

 **ERROR: nco_put_vara() failed to nc_put_vara() variable "xps_img"**

Any suggestions on how to proceed will be greatly appreciated. 

**Complete Error:**

```
2018-12-04 11:04:27,681 INFO    : extractor - [58f3be4e4f0c5bee63a521b7] VNIR - 2017-04-16__11-51-16-722 - invoking hyperspectral_workflow.sh to create: /home/extractor/sites/ua-mac/Level_1/vnir_netcdf/2017-04-16/2017-04-16__11-51-16-722/vnir_netcdf_L1_ua-mac_2017-04-16__11-51-16-722.nc

tput: No value for $TERM and no -T specified

tput: No value for $TERM and no -T specified

tput: No value for $TERM and no -T specified

Terraref hyperspectral data workflow invoked with:

hyperspectral_workflow.sh -d 1 -h -m /home/extractor/sites/ua-mac/Level_2/vnir_soil_masks/2017-04-16/2017-04-16__11-51-16-722/VNIR_L2_ua-mac_2017-04-16__11-51-16-722_soil_mask.nc --new_clb_mth -i /home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw -o /home/extractor/sites/ua-mac/Level_1/vnir_netcdf/2017-04-16/2017-04-16__11-51-16-722/vnir_netcdf_L1_ua-mac_2017-04-16__11-51-16-722.nc

Hyperspectral workflow scripts in directory /home/extractor

NCO version 4.7.6 from directory /usr/bin

Intermediate/temporary files written to directory /tmp

Final output stored in directory /home/extractor/sites/ua-mac/Level_1/vnir_netcdf/2017-04-16/2017-04-16__11-51-16-722

Input #00: /home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw

trn(in)  : /home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw

trn(out) : /tmp/terraref_tmp_trn.nc.pid495.fl00.tmp

ncks -O --hdr_pad=10000 --no_tmp_fl --trr_wxy=955,1600,2587 --trr typ_in=NC_USHORT --trr typ_out=NC_USHORT --trr ntl_in=bil --trr ntl_out=bsq --trr_in=/home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw /home/extractor/hyperspectral_dummy.nc /tmp/terraref_tmp_trn.nc.pid495.fl00.tmp

nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_put_vara()

nco_err_exit(): ERROR Error code is -101. Translation into English with nc_strerror(-101) is "NetCDF: HDF error"

ERROR: nco_put_vara() failed to nc_put_vara() variable "xps_img"

nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)

hyperspectral_workflow.sh: ERROR Failed to translate raw data. Debug this:

ncks -O  --hdr_pad=10000 --no_tmp_fl --trr_wxy=955,1600,2587 --trr typ_in=NC_USHORT --trr typ_out=NC_USHORT --trr ntl_in=bil --trr ntl_out=bsq --trr_in=/home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw /home/extractor/hyperspectral_dummy.nc /tmp/terraref_tmp_trn.nc.pid495.fl00.tmp

```

**Comment by Paheding** [comment] 2019-02-08 20:21
@czender Thanks for the prompt response. I opened the image in ENVI, the size looks good, see below:
![image](https://user-images.githubusercontent.com/24866799/52503950-9410a980-2bac-11e9-9566-4e5342567cd8.png)
We are checking on the NCO part now, will give you update once it's done. Thanks again!

**Comment by Paheding** [comment] 2019-02-08 20:42
@czender Here is the verion we installed the NCO in extractor docker file: https://github.com/terraref/extractors-hyperspectral/blob/master/hyperspectral/Dockerfile
netCDF version: libnetcdf13_4.6.1-3_amd64
Could you please to check above link? I am not quite sure about the incompatibility. Thanks.

**Comment by czender** [comment] 2019-02-08 21:13
The docker file tell me nothing useful.
Please run `ncremap --config` from the same NCO installation and post the results.
The netCDF error `NetCDF: HDF error` is pretty inscrutable. 
It's likely an environment or linking error, not an NCO source code error.
In other words, something changed on your end.
Can you run this from the command line?
`ncks -O  --hdr_pad=10000 --no_tmp_fl --trr_wxy=955,1600,2587 --trr typ_in=NC_USHORT --trr typ_out=NC_USHORT --trr ntl_in=bil --trr ntl_out=bsq --trr_in=/home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw /home/extractor/hyperspectral_dummy.nc /tmp/terraref_tmp_trn.nc.pid495.fl00.tmp`

**Comment by Paheding** [comment] 2019-02-11 19:00
@czender Thank you! We have run it the command line, and here is the output:

```
extractor@74fff32d347a:/home/clowder$ ncremap --config
ncremap, the NCO regridder and map- and grid-generator, version 4.7.6
Copyright (C) 2016--2018 Charlie Zender
This program is part of NCO, the netCDF Operators
NCO is free software and comes with a BIG FAT KISS and ABSOLUTELY NO WARRANTY
You may redistribute and/or modify NCO under the terms of the
GNU General Public License (GPL) Version 3 with exceptions described in the LICENSE file
GPL: http://www.gnu.org/copyleft/gpl.html
LICENSE: https://github.com/nco/nco/tree/master/LICENSE
Config: ncremap running from directory /usr/bin
Config: Calling NCO binaries in directory /usr/bin
Config: Binaries linked to netCDF library version 4.6.1
Config: No hardcoded path/module overrides
Config: ESMF weight-generation command ESMF_RegridWeightGen not found
Config: Tempest weight-generation command GenerateOfflineMap not found
```

**Comment by dlebauer** [comment] 2019-02-11 20:23
Output from the ncks statement:

```sh
extractor@4926d315127f:/home/clowder$ ncks -O --hdr_pad=10000 --no_tmp_fl --trr_wxy=955,1600,2587 --trr typ_in=NC_USHORT --trr typ_out=NC_USHORT --trr ntl_in=bil --trr ntl_out=bsq --trr_in=/home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw /home/extractor/hyperspectral_dummy.nc /tmp/terraref_tmp_trn.nc.pid495.fl00.tmp
ncks: ERROR unable to open binary output file /home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw
```

Makes me suspect that the file isn't present.

**Comment by dlebauer** [comment] 2019-02-11 20:27
Output from the ncks statement on the VM w/ directories mounted (from @max-zilla)

```sh
extractor@hyperspectral-6fcd1:/home/clowder$ ncks -O --hdr_pad=10000 --no_tmp_fl --trr_wxy=955,1600,2587 --trr typ_in=NC_USHORT --trr typ_out=NC_USHORT --trr ntl_in=bil --trr ntl_out=bsq --trr_in=/home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw /home/extractor/hyperspectral_dummy.nc /tmp/terraref_tmp_trn.nc.pid495.fl00.tmp
ERROR: nco_put_vara() failed to nc_put_vara() variable "xps_img"
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_put_vara()
nco_err_exit(): ERROR Error code is -101. Translation into English with nc_strerror(-101) is "NetCDF: HDF error"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
```

**Comment by czender** [comment] 2019-02-11 20:45
the `ncremap --config` output looks normal. The next step is to check whether ncks will convert a different BIL image to BSQ. This will tell us whether the problem is restricted to the image in the bug report or is pervasive. So run the same command on a different BIL input file (by changing argument to `trr_in`). Be sure to change the arguments to match the new dimension sizes (i.e., alter this if necessary `--trr_wxy=955,1600,2587`). The other options do not need to change. The `.tmp` file is the output.

**Comment by czender** [comment] 2019-02-11 21:21
Also I suggest running the above command with --dbg=1. That will produce additional debugging output. Please post it.

**Comment by Paheding** [comment] 2019-02-13 18:38
Hi Charlie, Thanks for the suggestion. Max have tested it on different BIL datasets and also tried running the hyperspectral_workflow.sh on other 2017 images and got the same error (var_xps). And here is output:

```
extractor@hyperspectral-316jc:/home/clowder$ ncks -O  --dbg=1 --hdr_pad=10000 --no_tmp_fl --trr_wxy=939,1600,2212 --trr typ_in=NC_USHORT --trr typ_out=NC_USHORT --trr ntl_in=bil --trr ntl_out=bsq --trr_in=/home/extractor/sites/ua-mac/raw_data/VNIR/2018-08-18/2018-08-18__11-47-47-403/aabc02a5-2fe1-4fdd-b26f-b87bf50c24fe_raw /home/extractor/hyperspectral_dummy.nc /tmp/terraref_tmp_trn.nc.pid595.fl00.tmp
ncks: INFO nco_trr_read() Terraref metadata: wvl_nbr = 939, xdm_nbr = 1600, ydm_nbr = 2212, ntl_typ_in = band_interleaved_by_line (BIL format), ntl_typ_out = band_sequential (BSQ format), var_typ_in = NC_USHORT, var_typ_out = NC_USHORT
ncks: INFO nco_trr_read() de-interleaving input image from ENVI type band_interleaved_by_line (BIL format)
ncks: INFO nco_trr_read() image diagnostics: min=0, max=25447, avg=878.152
ERROR: nco_put_vara() failed to nc_put_vara() variable "xps_img"
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_put_vara()
nco_err_exit(): ERROR Error code is -101. Translation into English with nc_strerror(-101) is "NetCDF: HDF error"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
```

**Comment by Paheding** [comment] 2019-02-19 21:09
@czender Just wondering if the above output provides you any useful information for resolving this issue? Thank you and look forward to hearing from you.

**Comment by czender** [comment] 2019-02-19 21:35
Send or make available to me the smallest BIL dataset you can that ncks fails. Include the command line that fails. I will see if I can reproduce the problem in my environment. I need to test my hypothesis that this is an environment issue not an NCO issue.

**Comment by czender** [comment] 2019-02-20 22:41
I received some kind of permission thing from GitHub. What I need is described above. A URL to the smallest known file that fails with ncks and the command line that it fails with. Thank you.

**Comment by Paheding** [comment] 2019-02-21 04:03
@czender Thank you, I will provide those as soon as possible.

**Comment by max-zilla** [comment] 2019-02-21 14:19
@czender I looked at the VNIR files by ascending size - I identified some smaller files, but those appeared to encounter a different error later in the process that involves opening the EnvironmentLogger netcdf files Henry generated. I'll include one of those outputs just for kicks, but the smallest file that encounters the xps_img bug is around 8 GB.

First, the bug discussed above:
https://terraref.ncsa.illinois.edu/clowder/datasets/58f3be4e4f0c5bee63a521b7
I believe you should still have access to Clowder. Raw file is 7.9 GB, is run with:
```
./hyperspectral_workflow.sh -d 1 -h --new_clb_mth -i /home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw -o 0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw.nc
```
...and outputs:
```
Terraref hyperspectral data workflow invoked with:
./hyperspectral_workflow.sh -d 1 -h --new_clb_mth -i /home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw -o 0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw.nc
Hyperspectral workflow scripts in directory /home/extractor
NCO version 4.7.6 from directory /usr/bin
Intermediate/temporary files written to directory /tmp
Final output stored in directory .
Input #00: /home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw
trn(in)  : /home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw
trn(out) : /tmp/terraref_tmp_trn.nc.pid271.fl00.tmp
ncks -O --hdr_pad=10000 --no_tmp_fl --trr_wxy=955,1600,2587 --trr typ_in=NC_USHORT --trr typ_out=NC_USHORT --trr ntl_in=bil --trr ntl_out=bsq --trr_in=/home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw /home/extractor/hyperspectral_dummy.nc /tmp/terraref_tmp_trn.nc.pid271.fl00.tmp
ERROR: nco_put_vara() failed to nc_put_vara() variable "xps_img"
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_put_vara()
nco_err_exit(): ERROR Error code is -101. Translation into English with nc_strerror(-101) is "NetCDF: HDF error"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
hyperspectral_workflow.sh: ERROR Failed to translate raw data. Debug this:
ncks -O  --hdr_pad=10000 --no_tmp_fl --trr_wxy=955,1600,2587 --trr typ_in=NC_USHORT --trr typ_out=NC_USHORT --trr ntl_in=bil --trr ntl_out=bsq --trr_in=/home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw /home/extractor/hyperspectral_dummy.nc /tmp/terraref_tmp_trn.nc.pid271.fl00.tmp
```


Here is a Clowder link to a dataset from April 2017 with a 88 MB raw file:
https://terraref.ncsa.illinois.edu/clowder/datasets/598d0c9d4f0c7dbcc83a05d5
The command from the extractor:
```
./hyperspectral_workflow.sh -d 1 -h --new_clb_mth -i /home/extractor/sites/ua-mac/raw_data/VNIR/2017-08-06/2017-08-06__16-05-45-497/9d4867a3-7920-454b-9f5a-c6b33dec3a1a_raw -o 9d4867a3-7920-454b-9f5a-c6b33dec3a1a_raw.nc
```
...and the output:
```
Terraref hyperspectral data workflow invoked with:
./hyperspectral_workflow.sh -d 1 -h --new_clb_mth -i /home/extractor/sites/ua-mac/raw_data/VNIR/2017-08-06/2017-08-06__16-05-45-497/9d4867a3-7920-454b-9f5a-c6b33dec3a1a_raw -o 9d4867a3-7920-454b-9f5a-c6b33dec3a1a_raw.nc
Hyperspectral workflow scripts in directory /home/extractor
NCO version 4.7.6 from directory /usr/bin
Intermediate/temporary files written to directory /tmp
Final output stored in directory .
Input #00: /home/extractor/sites/ua-mac/raw_data/VNIR/2017-08-06/2017-08-06__16-05-45-497/9d4867a3-7920-454b-9f5a-c6b33dec3a1a_raw
trn(in)  : /home/extractor/sites/ua-mac/raw_data/VNIR/2017-08-06/2017-08-06__16-05-45-497/9d4867a3-7920-454b-9f5a-c6b33dec3a1a_raw
trn(out) : /tmp/terraref_tmp_trn.nc.pid108.fl00.tmp
ncks -O --hdr_pad=10000 --no_tmp_fl --trr_wxy=955,1600,29 --trr typ_in=NC_USHORT --trr typ_out=NC_USHORT --trr ntl_in=bil --trr ntl_out=bsq --trr_in=/home/extractor/sites/ua-mac/raw_data/VNIR/2017-08-06/2017-08-06__16-05-45-497/9d4867a3-7920-454b-9f5a-c6b33dec3a1a_raw /home/extractor/hyperspectral_dummy.nc /tmp/terraref_tmp_trn.nc.pid108.fl00.tmp
att(in)  : /tmp/terraref_tmp_trn.nc.pid108.fl00.tmp
att(out) : /tmp/terraref_tmp_att.nc.pid108.fl00.tmp
ncatted -O --gaa terraref_script=hyperspectral_workflow.sh --gaa workflow_invocation="'./hyperspectral_workflow.sh -d 1 -h --new_clb_mth -i /home/extractor/sites/ua-mac/raw_data/VNIR/2017-08-06/2017-08-06__16-05-45-497/9d4867a3-7920-454b-9f5a-c6b33dec3a1a_raw -o 9d4867a3-7920-454b-9f5a-c6b33dec3a1a_raw.nc'" --gaa terraref_hostname=hyperspectral-lkz46 --gaa terraref_version=4.7.6 -a "Conventions,global,o,c,CF-1.5" -a "Project,global,o,c,TERRAREF" --gaa history="Thu Feb 21 13:56:36 UTC 2019: ./hyperspectral_workflow.sh -d 1 -h --new_clb_mth -i /home/extractor/sites/ua-mac/raw_data/VNIR/2017-08-06/2017-08-06__16-05-45-497/9d4867a3-7920-454b-9f5a-c6b33dec3a1a_raw -o 9d4867a3-7920-454b-9f5a-c6b33dec3a1a_raw.nc" /tmp/terraref_tmp_trn.nc.pid108.fl00.tmp /tmp/terraref_tmp_att.nc.pid108.fl00.tmp
jsn(in)  : /home/extractor/sites/ua-mac/raw_data/VNIR/2017-08-06/2017-08-06__16-05-45-497/9d4867a3-7920-454b-9f5a-c6b33dec3a1a_raw
jsn(out) : /tmp/terraref_tmp_jsn.nc.pid108
python /home/extractor/hyperspectral_metadata.py dbg=yes fmt=4 ftn=no /home/extractor/sites/ua-mac/raw_data/VNIR/2017-08-06/2017-08-06__16-05-45-497/9d4867a3-7920-454b-9f5a-c6b33dec3a1a_raw /tmp/terraref_tmp_jsn.nc.pid108.fl00.tmp
ERROR: nco__open() unable to open file "/home/extractor/sites/ua-mac/Level_1/envlog_netcdf/2017-08-06/envlog_netcdf_L1_ua-mac_2017-08-06.nc"
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__open()
nco_err_exit(): ERROR Error code is -101. Translation into English with nc_strerror(-101) is "NetCDF: HDF error"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
```

In this case, the problem involves opening up this EnvironmentLogger file:
https://terraref.ncsa.illinois.edu/clowder/datasets/59e773a54f0c94c7194e51d7
(12.1 MB)

Any insight you can offer is helpful. The brief summary of this is that we had trouble running hyperspectral in our pipeline due to the memory requirements, so in late 2017 Henry B. ran a custom job script on the ROGER system to process the 2017 data. Apparently he was utilizing the environment logger data and had a requirement that they be chronological netCDFs, which wasn't discussed prior to that, so he regenerated a bunch of them to suit his needs (I believe the file linked above is an example) and ran that.

The whole process was a bit of a black box from our end, and now that we're trying to run at least some of the VNIR data in our docker extractor pipeline with a 128 GB memory node, we're running into errors at every turn and are having a very difficult time debugging. I'd asked @Paheding and his team to look at the shell script after I'd had little time/success digging into it, and that's how we've gotten here. I'm quite ready to accept that our docker installation process has the wrong versions of something and/or there's something at our end (installation code is here: https://github.com/terraref/extractors-hyperspectral/blob/master/hyperspectral/Dockerfile#L22) and I'm not sure what environment Patrick is looking at or if he's using the docker image, but your time on this is really appreciated.

**Comment by czender** [comment] 2019-02-21 18:03
Accessing all Terraref links in the above results in:
```
Account not active
Your account has not been enabled. If you feel this in error please use the contact admin form to ask the server admins about your account.

```
All I need is a working HTML link to the dataset.

**Comment by Paheding** [comment] 2019-02-21 18:13
@czender Thanks for letting us know this issue. @max-zilla have granted you the access a few minutes ago, you may give it a try again. Thanks.

**Comment by dlebauer** [comment] 2019-02-21 18:28
I've made all of the datasets public so all of the urls above should work without requiring any permissions for anyone.

**Comment by Paheding** [comment] 2019-02-21 18:52
@czender Thank you.

**Comment by czender** [comment] 2019-02-21 19:32
The first result is in, and confirms that the culprit is most likely a build/link/library issue with the netCDF/HDF libraries. I suggest Terraref update or downgrade the netCDF+HDF5 libraries used. An "HDF Error" is almost always a library (i.e., not an NCO) bug from either netCDF or HDF5 or issues with compiling (e.g., mismatched headers from different versions). Here is the output on my workstation for the test file I just downloaded. My guess is that any of you can repeat success with this command if you transfer the raw BIL file to your local machine and use any NCO version installed from Conda or any other build system (other than the current Terraref Docker build):
```
(base) zender@firn:~/data/terraref$ ncks -O --hdr_pad=10000 --no_tmp_fl --trr_wxy=955,1600,2587 --trr typ_in=NC_USHORT --trr typ_out=NC_USHORT --trr ntl_in=bil --trr ntl_out=bsq --trr_in=${DATA}/terraref/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw ~/nco/data/in.nc ~/terraref_foo.nc
(base) zender@firn:~/data/terraref$ ls -l ~/terraref_foo.nc 
-rw-r--r-- 1 zender staff 7905879358 Feb 21 11:02 /Users/zender/terraref_foo.nc
(base) zender@firn:~/data/terraref$ ncks -m -M ~/terraref_foo.nc 
netcdf terraref_foo {
  dimensions:
    wavelength = 955 ;
    x = 1600 ;
    y = 2587 ;

  variables:
    ushort xps_img(wavelength,y,x) ;
      xps_img:long_name = "Exposure counts" ;
      xps_img:meaning = "Counts on scale from 0 to 2^16-1 = 65535" ;
      xps_img:units = "1" ;

  // global attributes:
    :title = "None given (supply with --trr ttl=\"Title\")" ;
    :created_by = "nobody" ;
    :history = "ncks -O --hdr_pad=10000 --no_tmp_fl --trr_wxy=955,1600,2587 --trr typ_in=NC_USHORT --trr typ_out=NC_USHORT --trr ntl_in=bil --trr ntl_out=bsq --trr_in=/Users/zender/data/terraref/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw /Users/zender/nco/data/in.nc /Users/zender/terraref_foo.nc" ;

} // group /

```
When rebuilding the libraries, pay particular attention to any warnings reported during the builds. Given that both ERRORS Max describes above are "HDF errors", I suspect that fixing the libraries will fix both problems.

**Comment by czender** [comment] 2019-02-21 20:01
Docker is above my paygrade, yet it seems to me that the weakness in the Docker file Max points to above is that it is pinned to a bunch of specific .deb versions. Perhaps there's a bad interaction between two of those that only shows up with certain filetypes/sizes/access patterns. A more robust way to avoid such problems might be to use the conda-forge versions of all those packages, since conda-forge is pretty reliable at reducing library mismatch errors.

**Comment by czender** [comment] 2019-02-22 16:57
It seems like this issue has held up Terraflow processing for some time. To verify whether a problem is a build-issue or a "real bug" (something I need to be involved in solving) moving forward, here is a strategy to consider. The hyperspectral workflow is modular and is essentially a script that creates the intricate arguments to a half dozen processing steps, each of which looks intimidating as a command though it is conceptually simple. When the workflow breaks it spits-out the exact command that failed. If the reason for the failure is not obvious (e.g., out-of-disk-space), then copy the inputs to the commands to another environment with a stock, off-the-shelf NCO (rather than the homebrew Docker environment), change the arguments to the broken command appropriately, and see if it executes correctly in the new environment. That will verify whether or not it is an environment error. It would be good practice and reassuring to do that now. Following my example above will de-mystify the workflow a bit and reassure us all that we have the correct diagnosis.

**Comment by Paheding** [comment] 2019-02-22 17:08
@czender Thanks for suggestions. We will start by updating or downgrading the netCDF+HDF5 libraries. Then move forward to the next step.

**Comment by max-zilla** [comment] 2019-02-28 21:19
@czender thanks for your help thus far. I rewrote the Dockerfile (basically a way to install the stuff you need on a relatively blank VM) to install conda and use forge pkgs for hdf5, netcdf, nco:
```
# install conda
USER extractor
RUN cd ~ \
    &&  wget https://repo.continuum.io/archive/Anaconda2-5.3.1-Linux-x86_64.sh \
    && bash Anaconda2-5.3.1-Linux-x86_64.sh -b

#install conda-forge packages
RUN ~/anaconda2/bin/conda config --add channels conda-forge \
    && ~/anaconda2/bin/conda install hdf5 netcdf4 nco
```

I did this, deployed on our big-memory node, and ran the command again on the 7.8 GB file and replicated your output:
```
$ ~/anaconda2/bin/ncks -O --hdr_pad=10000 --no_tmp_fl --trr_wxy=955,1600,2587 --trr typ_in=NC_USHORT --trr typ_out=NC_USHORT --trr ntl_in=bil --trr ntl_out=bsq --trr_in=/home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw ~/hyperspectral_dummy.nc /tmp/terraref_foo.nc

$ ls /tmp
terraref_foo.nc

$ ~/anaconda2/bin/ncks -m -M /tmp/terraref_foo.nc 
netcdf terraref_foo {
  dimensions:
    wavelength = 955 ;
    x = 1600 ;
    y = 2587 ;

  variables:
    ushort xps_img(wavelength,y,x) ;
      xps_img:long_name = "Exposure counts" ;
      xps_img:meaning = "Counts on scale from 0 to 2^16-1 = 65535" ;
      xps_img:units = "1" ;

  // global attributes:
    :title = "None given (supply with --trr ttl=\"Title\")" ;
    :created_by = "nobody" ;
    :history = "/home/extractor/anaconda2/bin/ncks -O --hdr_pad=10000 --no_tmp_fl --trr_wxy=955,1600,2587 --trr typ_in=NC_USHORT --trr typ_out=NC_USHORT --trr ntl_in=bil --trr ntl_out=bsq --trr_in=/home/extractor/sites/ua-mac/raw_data/VNIR/2017-04-16/2017-04-16__11-51-16-722/0eebf84b-8a0a-45e6-aa2a-c49c82fab5e9_raw /home/extractor/hyperspectral_dummy.nc /tmp/terraref_foo.nc" ;

} // group /
```
This is very promising! We can try from our pipeline again to see if I can get the EnvironmentLogger bit working as well. Thanks for your help and time, will update more when we make more progress.

**Comment by czender** [comment] 2019-02-28 21:30
Glad to hear it, @max-zilla

**Comment by czender** [comment] 2019-03-07 16:46
Closing this. Feel free to re-open if necessary.

**Closed by czender** 2019-03-07 16:46 UTC
