### ISSUE TITLE
ncremap pure pressure vertical interpolation does only the first timestep, everything else is zeros

### ISSUE THREAD

**Issue by prajeeshag** [nco/nco#266] opened 2023-04-02 14:08 UTC
ncremap vertical interpolation is only doing it for the first timestep. I checked with different versions from 5.1.2 to 5.1.5. All are having the same problem.

ncap2 -O -v -s 'defdim("plev",17);plev[$plev]={100000,92500,85000, 70000,60000,50000,40000,30000,25000,20000,15000,10000,7000,5000, 3000,2000,1000};' vrt_prs_ncep_L17.nc
ncremap --vrt_out=vrt_prs_ncep_L17.nc in_data.nc out.nc

All values after the first timestep in "out.nc" are zero.  "in_data.nc" is attached here.

[test_ncremap_vrt.tar.gz](https://github.com/nco/nco/files/11132393/test_ncremap_vrt.tar.gz)

**Comment by czender** [comment] 2023-04-03 23:56
Thanks for reporting this. I can reproduce the issue. It only occurs, to my knowledge, when interpolating from pressure to pressure grids, which apparently I have never tried with multi-timestep input. It looks like handling time-varying input was not implemented. Now it's on my list. Will post again when I have an update.

**Comment by czender** [comment] 2023-04-05 21:01
The latest development snapshot, NCO 5.1.6-alpha02, fixes this issue for me. Please test it if you can and provide feedback. Otherwise, these changes will be in NCO 5.1.6-final in a few weeks. This shows the first two timesteps of the output of your test case:

```
zender@spectral:~/Downloads$ ncks --version
NCO netCDF Operators version 5.1.6-alpha02 "Indictment Excitement" built by zender on spectral at Apr  5 2023 13:54:19
ncks version 5.1.6-alpha02
zender@spectral:~/Downloads$ ncremap --vrt_out=${DATA}/grids/vrt_prs_ncep_L17.nc in_data.nc out.nc
Input #00: /Users/zender/Downloads/in_data.nc
Vertical : /Users/zender/data/grids/vrt_prs_ncep_L17.nc
zender@spectral:~/Downloads$ ncks -C -v var130 -d time,0,1 -d lat,0 -d lon,0 out.nc
netcdf out {
  dimensions:
    lat = 1 ;
    lon = 1 ;
    plev = 17 ;
    time = UNLIMITED ; // (2 currently)

  variables:
    float var130(time,plev,lat,lon) ;
      var130:code = 130 ;
      var130:table = 128 ;
      var130:CDI_grid_type = "gaussian" ;
      var130:CDI_grid_num_LPE = 96 ;

  data:
    var130 = 
    269.0848, 
    264.1151, 
    259.9385, 
    254.1309, 
    248.1047, 
    239.911, 
    229.4799, 
    221.6631, 
    223.5385, 
    225.9229, 
    225.8931, 
    225.3141, 
    225, 
    224.9623, 
    225.4269, 
    226.6538, 
    230.6947, 
    269.1624, 
    264.223, 
    260.0998, 
    254.2092, 
    248.2053, 
    239.7696, 
    229.239, 
    221.7161, 
    223.7113, 
    225.8742, 
    225.8563, 
    225.1939, 
    225.0779, 
    224.8645, 
    225.2074, 
    226.8029, 
    230.4969 ;

} // group /

```

**Comment by prajeeshag** [comment] 2023-04-06 05:43
Yes, it is working with 5.1.6-alpha02. Thanks.

**Closed** 2023-04-06 15:12 UTC
